Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/lib/python3/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
resultados = busca('"filho de"')
# print(resultados,type(resultados[0]), len(resultados[0]))
# type(resultados)
print('Resultados:', len(resultados))
for res in resultados[:10]:
    print(res[0]['title'])
    display(HTML(res[1]))
    print()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [6][0m, in [0;36m<cell line: 5>[0;34m()[0m
[1;32m      5[0m [38;5;28;01mfor[39;00m res [38;5;129;01min[39;00m resultados[:[38;5;241m10[39m]:
[1;32m      6[0m     [38;5;28mprint[39m(res[[38;5;241m0[39m][[38;5;124m'[39m[38;5;124mtitle[39m[38;5;124m'[39m])
[0;32m----> 7[0m     display([43mHTML[49m(res[[38;5;241m1[39m]))
[1;32m      8[0m     [38;5;28mprint[39m()

[0;31mNameError[0m: name 'HTML' is not defined
NameError: name 'HTML' is not defined

